[flags]
#battery = true
disable_gpu = false
rate = 1000
default_time_value = "120s"
time_delta = 15000
show_table_scroll_position = true
#show_table_scroll_bar = true
retention = "30m"
autohide_time = true
#hide_time = true
table_gap = "none"

[processes]
# PID, Name, CPU%, Mem%, R/s, W/s, T.Read, T.Write, User, State, Time, GMem%, GPU%
columns = ["Name", "CPU%", "GPU%", "Mem%", "GMem%", "User", "Time"]
hide_k_threads = true
get_threads = false
process_command = false
default_memory_value = true
default_tree = true
disable_advanced_kill = false
default_sort = "mem"

[cpu]
# "all", "average"/"avg"
default = "average"
show_decimal = true
left_legend = true

[memory_graph]
legend_position = "top-left"
short_gpu_names = true

[temperature]
[temperature.sensor_filter]
is_list_ignored = true
list = ["sensor", "package"]
#regex = false
#case_sensitive = false
#whole_word = false


[disk]
# Disk, Mount, Used, Free, Total, Used%, Free%, R/s, W/s
columns = ["Mount", "Total", "Free"]
#default_sort = "Mount"
include_unmounted = false

#[disk.mount_filter]
#is_list_ignored = true
#list = ["/boot"]


#[network_graph]
#legend_position = "top-left"

[styles] # Uncomment if you want to use custom styling
# Built-in themes. Valid values are:
# - "default"
# - "default-light"
# - "gruvbox"
# - "gruvbox-light"
# - "nord"
# - "nord-light".
#
# This will have the lowest precedence if a custom colour palette is set,
# or overridden if the command-line flag for a built-in theme is set.
theme = "nord-light"

#[styles.cpu]
#all_entry_color = "green"
#avg_entry_color = "red"
#cpu_core_colors = ["light magenta", "light yellow", "light cyan", "light green", "light blue", "cyan", "green", "blue"]

#[styles.memory]
#ram_color = "light magenta"
#cache_color = "light red"
#swap_color = "light yellow"
#arc_color = "light cyan"
#gpu_colors = ["light blue", "light red", "cyan", "green", "blue", "red"]

#[styles.network]
#rx_color = "light magenta"
#tx_color = "light yellow"
#rx_total_color = "light cyan"
#tx_total_color = "light green"

#[styles.battery]
#high_battery_color = "green"
#medium_battery_color = "yellow"
#low_battery_color = "red"

#[styles.tables]
#headers = {color = "light blue", bold = true}

#[styles.graphs]
#graph_color = "gray"
#legend_text = {color = "gray"}

#[styles.widgets]
#border_color = "gray"
#selected_border_color = "light blue"
#widget_title = {color = "gray"}
#text = {color = "gray"}
#selected_text = {color = "black", bg_color = "light blue"}
#disabled_text = {color = "dark gray"}

# Layout - layouts follow a pattern like this:
# [[row]] represents a row in the application.
# [[row.child]] represents either a widget or a column.
# [[row.child.child]] represents a widget.
#
# All widgets must have the type value set to one of ["cpu", "mem", "proc", "net", "temp", "disk", "empty"].

[[row]]
  ratio=2
  [[row.child]]
  ratio=25
  type="cpu"
  [[row.child]]
  ratio=25
  type="mem"
[[row]]
  ratio=5
  [[row.child]]
  ratio=1
    [[row.child.child]]
    ratio=20
    type="temp"
    [[row.child.child]]
    ratio=15
    type="disk"
    [[row.child.child]]
    ratio=15
    type="batt"
  [[row.child]]
  	ratio=3
    type="proc"
    default=true


#[[row]]
#  [[row.child]]
#  ratio=2
#    [[row.child.child]]
#    ratio=26
#    type="cpu"
#    [[row.child.child]]
#    ratio=19
#    type="mem"
#    [[row.child.child]]
#    ratio=20
#    type="temp"
#    [[row.child.child]]
#    ratio=10
#    type="disk"
#  [[row.child]]
#    ratio=3
#    type="proc"
#    default=true