include current-theme.conf

# Wayland app ID (helps with notification focusing)
#linux_display_server wayland
#wayland_enable_ime no

font_size 15.0
cursor_shape beam
cursor_trail 1
scrollback_lines 50000
#scrollback_pager ov --jump-target 50%
scrollback_pager /home/pavel/.config/kitty/pager.sh
wheel_scroll_multiplier 5.0
touch_scroll_multiplier 1.0
open_url_with default
underline_hyperlinks hover
copy_on_select clipboard
clear_selection_on_clipboard_loss yes
strip_trailing_spaces smart
focus_follows_mouse yes
click_interval 0.2
repaint_delay 5
#window_padding_width 0 4
confirm_os_window_close 0
enable_audio_bell no

tab_bar_edge top
tab_bar_margin_width 0.0
tab_bar_margin_height 0.0 0.0
tab_bar_style custom
tab_bar_align center
tab_bar_min_tabs 2







shell /usr/bin/zsh
editor /usr/bin/subl
update_check_interval 0
font_family      Jetbrains Mono NerdFont
bold_font        auto
italic_font      auto
bold_italic_font auto
scrollbar always
scrollbar_interactive yes
scrollbar_jump_on_click yes
scrollbar_gap 0
scrollbar_width 0.5
scrollbar_hover_width 0.5
scrollbar_handle_opacity 0.2
scrollbar_track_opacity 0.0
scrollbar_track_hover_opacity 0.0

#Shift + select always selects
#ctrl+alt + select - select in columns

#: Search and highlight text in scrollback
map kitty_mod+f launch --location=hsplit --allow-remote-control kitty +kitten search.py @active-kitty-window-id
mark1_foreground red
mark1_background gray
map kitty_mod+up scroll_to_mark prev
map kitty_mod+down scroll_to_mark next
map escape combine : remove_marker : send_key escape

allow_remote_control yes
listen_on unix:@mykitty
allow_cloning yes
notify_on_cmd_finish unfocused 5
command_on_bell none
notification_close_on_focus yes

#startup_session ~/.config/kitty/startup.session


#map f3 launch --allow-remote-control kitty +kitten broadcast
#map f3 launch --allow-remote-control kitty +kitten broadcast --match-tab state:focused

mouse_map right press ungrabbed mouse_select_command_output
# clone-in-kitty --type=tab #clone current window to new tab
# kitten run-shell (OPTIONALY --shell=/bin/bash) #enable shell integration inside containers (kitten binary must be installed)

cursor_stop_blinking_after 0
cursor_blink_interval 15

# Ctrl+Click on hyperlinks in apps that grab mouse (like pacsea)
mouse_map left click grabbed,ungrabbed mouse_handle_click selection link prompt

#: Smart tab right (switch to next tab, or create new if on last tab)
map kitty_mod+right kitten smart_tab_right.py

#: Smart tab left (switch to previous tab, or create new at index 0 if on first tab)
map kitty_mod+left kitten smart_tab_left.py



map kitty_mod+z send_text all \x1b[122;6u
map kitty_mod+backspace send_text all \x1b[127;6u


map ctrl+shift+minus change_font_size all -0.3
map ctrl+shift+equal change_font_size all +0.3
