# Run script files in current window
protocol file
ext sh,command,tool,bash,zsh,fish,py
action send_text all '${FILE_PATH}'\r
action scroll_end

# CD into directories in current window
protocol file
mime inode/directory
action send_text all cd '${FILE_PATH}'\r
action scroll_end

# Display image files inline with icat
protocol file
mime image/*
action send_text all kitten icat '${FILE_PATH}'\r
action scroll_end

# PDF - browser
protocol file
mime application/pdf
action launch --type=background xdg-open -- $FILE_PATH

# Torrents - open in mpv
protocol file
mime application/bittorrent
action launch --type=background mpv -- $FILE_PATH

# Audio/Video - open in mpv
protocol file
mime {audio,video}/*
action launch --type=background mpv -- $FILE_PATH

# Archives - extract into a folder named after the archive
protocol file
mime application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}
action send_text all d=$(basename '${FILE_PATH}'); d=${d%%.*}; mkdir -p "$d" && bsdtar -xf '${FILE_PATH}' -C "$d" && ls "$d"\r
action scroll_end

# Text/JSON/JS/empty - open in subl
protocol file
mime text/*,application/json,application/ndjson,*/javascript,inode/empty
action launch --type=background subl -- $FILE_PATH

# Fallback - xdg-open
protocol file
action launch --type=background xdg-open -- $FILE_PATH

# Open ssh URLs with kitten ssh in current window
protocol ssh
action send_text all kitten ssh $URL\r
action scroll_end

# Open http/https URLs in default browser
protocol http,https
action launch --type=background xdg-open $URL
