WHEEL_UP        add speed  0.1
WHEEL_DOWN      add speed -0.1
MBTN_RIGHT      set speed  1
MBTN_LEFT       cycle pause
Ctrl+RIGHT      add chapter +1
Ctrl+LEFT       add chapter -1

#NEXT playlist-next
#PREV playlist-prev
#MBTN_BACK playlist-prev
#MBTN_FORWARD playlist-next
#Alt+LEFT playlist-prev
#Alt+RIGHT playlist-next
#Alt+UP playlist-prev
#Alt+DOWN playlist-next

#       add script bindings

g-p script-binding select/select-playlist keep-open
g-s script-binding select/select-sid keep-open
g-S script-binding select/select-secondary-sid keep-open
g-a script-binding select/select-aid keep-open
g-v script-binding select/select-vid keep-open
g-t script-binding select/select-track keep-open
g-c script-binding select/select-chapter keep-open
g-e script-binding select/select-edition keep-open
g-l script-binding select/select-subtitle-line keep-open
g-L script-binding select/select-secondary-subtitle-line keep-open
g-d script-binding select/select-audio-device keep-open
g-h script-binding select/select-watch-history keep-open
g-w script-binding select/select-watch-later keep-open
g-b script-binding select/select-binding keep-open
g-r script-binding select/show-properties keep-open