WHEEL_UP        add speed  0.1
WHEEL_DOWN      add speed -0.1
MBTN_RIGHT      set speed  1
MBTN_LEFT       cycle pause
Ctrl+RIGHT      add chapter +1
Ctrl+LEFT       add chapter -1

#NEXT playlist-next
#PREV playlist-prev
#MBTN_BACK playlist-prev
#MBTN_FORWARD playlist-next
#Alt+LEFT playlist-prev
#Alt+RIGHT playlist-next
#Alt+UP playlist-prev
#Alt+DOWN playlist-next

#       add script bindings
