vo=gpu-next
gpu-api=vulkan
hwdec=vulkan
hwdec-codecs = h264,vc1,hevc,vp8,vp9,av1
target-colorspace-hint = no
target-colorspace-hint-mode = source

scale = ewa_lanczossharp
scale-antiring = 0.4
cscale = ewa_lanczossharp
dscale = ewa_robidoux # Polar Catmull-Rom (0.0, 0.5)
dscale-param1 = 0.0
dscale-param2 = 0.5
dscale-antiring = 0.5
correct-downscaling = yes
sigmoid-upscaling = yes
dither-depth = 8 # Set to your displays bitdepth.
dither = fruit # Change to "ordered" if 10 or 12 bit display.
deband = no

fullscreen=yes
force-window=immediate
video-sync=display-resample
save-position-on-quit=yes
alang=en,eng,english,enGB,en-GB,English,enUS,en-US,en-orig,en-en
slang=en,eng,english,enGB,en-GB,English,enUS,en-US,en-orig,en-en
osc=no
osd-bar=no
border=no
keep-open=yes
cache-on-disk=no
msg-level=all=info

sub-auto = fuzzy
sub-font = "JetBrainsMono-NF-Medium"
sub-font-size = 52
sub-color = 0.95/0.95/0.95/1
sub-blur = 0.2
sub-bold = yes
sub-border-size = 3
sub-border-color = 0.05/0.05/0.05/1
sub-spacing = 1.5
sub-shadow-offset = 1
sub-shadow-color = 0/0/0/0.25
sub-use-margins = no
sub-margin-y = 50
sub-margin-x = 80
sub-scale-with-window = no
sub-ass-override = no
demuxer-mkv-subtitle-preroll = yes
sub-fix-timing = no
blend-subtitles = yes
sub-gray = yes
sub-gauss = .65

[Skip Complex Scaling]
profile-desc = "No complex scaling needed - 1:1 pixel ratio"
profile-cond = (p["video-params/w"] or 0) > 0 and (p["video-params/h"] or 0) > 0 and (p["osd-dimensions/w"] or 0) > 0 and (p["osd-dimensions/h"] or 0) > 0 and (p["video-params/w"] >= p["osd-dimensions/w"] or p["video-params/h"] >= p["osd-dimensions/h"])
scale = bilinear
cscale = bilinear
sigmoid-upscaling = no
profile-restore = copy

[Analog bt.470m]
profile-desc = "Analog bt.470m"
profile-cond = p["video-params/primaries"]=="bt.470m"
target-prim = bt.470m
target-trc = bt.1886
profile-restore = copy

[SD NTSC]
profile-desc = "SD NTSC"
profile-cond = p["video-params/primaries"]=="bt.601-525"
target-prim = bt.601-525
target-trc = bt.1886
profile-restore = copy

[SD PAL]
profile-desc = "SD PAL"
profile-cond = p["video-params/primaries"]=="bt.601-625"
target-prim = bt.601-625
target-trc = bt.1886
profile-restore = copy

[SDR UHD & HD BT.709]
profile-desc = "SDR UHD & HD BT.709"
profile-cond = p["video-params/primaries"]=="bt.709"
target-prim = bt.709
target-trc = bt.1886
profile-restore = copy

[SDR UHD BT.2020]
profile-desc = "SDR UHD BT.2020"
profile-cond = p["video-params/gamma"]~="pq" and p["video-params/primaries"]=="bt.2020" and p["video-params/gamma"]=="bt.1886"
target-prim = bt.709
target-trc = bt.1886
gamut-mapping-mode = absolute
profile-restore = copy

[HDR WEBDL & Blu-ray / DV Blu-ray]
profile-desc = "HDR WEBDL & Blu-ray / DV Blu-ray"
profile-cond = p["video-params/gamma"]=="pq" and p["video-params/primaries"]=="bt.2020" and p["video-params/colorlevels"]~="full"
tone-mapping = spline
target-prim = bt.709
target-trc = bt.1886
hdr-compute-peak = yes
gamut-mapping-mode = perceptual
target-peak = 120
screenshot-tag-colorspace = no
profile-restore = copy

[DV WEBDL]
profile-desc = "DV WEBDL"
profile-cond = p["video-params/hw-pixelformat"]=="p010" and p["video-params/colorlevels"]=="full" and p["video-params/colormatrix"]=="dolbyvision"
tone-mapping = bt.2446a
target-prim = bt.709
target-trc = bt.1886
hdr-compute-peak = yes
gamut-mapping-mode = perceptual
target-peak = 120
screenshot-tag-colorspace = no
profile-restore = copy
