shell=zsh
selection-target=clipboard #primary #clipboard #both
# workers=<number of logical CPUs>

font=Jetbrains Mono NerdFont:weight=bold:size=12
# font-bold=<bold variant of regular font>
# font-italic=<italic variant of regular font>
# font-bold-italic=<bold+italic variant of regular font>
# dpi-aware=no
font-size-adjustment=1
#box-drawings-uses-font-glyphs=yes
#gamma-correct-blending=no

#pad=25x25 #center-when-maximized-and-fullscreen #center
resize-delay-ms=0
initial-window-mode=maximized

[environment]
# name=value

[bell]
# system=yes
# urgent=no
# notify=no
# visual=no
# command=
# command-focused=no

[desktop-notifications]
# command=notify-send --wait --app-name ${app-id} --icon ${app-id} --category ${category} --urgency ${urgency} --expire-time ${expire-time} --hint STRING:image-path:${icon} --hint BOOLEAN:suppress-sound:${muted} --hint STRING:sound-name:${sound-name} --replace-id ${replace-id} ${action-argument} --print-id -- ${title} ${body}
# command-action-argument=--action ${action-name}=${action-label}
# close=""
# inhibit-when-focused=yes

[scrollback]
lines=50000
multiplier=1.0
# indicator-position=relative #fixed #relative #none
# indicator-format=line #line #percentage

[url]
# launch=xdg-open ${url}
# label-letters=sadfjklewcmpgh
osc8-underline=always #url-mode

[cursor]
style=beam #block #beam #underline #hollow
unfocused-style=unchanged #hollow #none #unchanged
# color=130F0F ede0de
blink=yes
blink-rate=500
beam-thickness=1.5
# underline-thickness=<font underline thickness>

[mouse]
# hide-when-typing=no


[colors]
# alpha=1.0
# alpha-mode=default # Can be `default`, `matching` or `all`
background=0d1117
foreground=d0d7de
# cursor=<inverse foreground/background>
# flash=7f7f00
# flash-alpha=0.5

### Normal/regular colors (color palette 0-7)
regular0=524345  # black
regular1=ff7b72  # red
regular2=3fb950  # green
regular3=d29922  # yellow
regular4=539bf5  # blue
regular5=bc8cff  # magenta
regular6=39c5cf  # cyan
regular7=d6c2c3  # white
#
### Bright colors (color palette 8-15)
#bright0=524345   # bright black
#bright1=ffb2bd   # bright red
#bright2=e5bdc1   # bright green
#bright3=eabf90   # bright yellow
#bright4=524345   # bright blue
#bright5=e5bdc1   # bright magenta
#bright6=eabf90   # bright cyan
#bright7=d6c2c3   # bright white

## dimmed colors (see foot.ini(5) man page)
# dim0=<not set>
# dim1=<not set>
# dim2=<not set>
# dim3=<not set>
# dim4=<not set>
# dim5=<not set>
# dim6=<not set>
# dim7=<not-set>


## Misc colors
# selection-foreground=<inverse foreground/background>
# selection-background=<inverse foreground/background>
# jump-labels=<regular0> <regular3>          # black-on-yellow
# scrollback-indicator=<regular0> <bright4>  # black-on-bright-blue
# search-box-no-match=<regular0> <regular1>  # black-on-red
# search-box-match=<regular0> <regular3>     # black-on-yellow
# urls=<regular3>


[key-bindings]
# scrollback-home=none
# scrollback-end=none
# clipboard-copy=Control+Shift+c XF86Copy
# clipboard-paste=Control+Shift+v XF86Paste
# primary-paste=Shift+Insert
search-start=Control+Shift+f
font-increase=Control+Shift+plus Control+Shift+equal
font-decrease=Control+Shift+minus
# font-reset=Control+0 Control+KP_0
# spawn-terminal=Control+Shift+n
show-urls-launch=none
# show-urls-copy=none
show-urls-persistent=Control+Shift+o
prompt-prev=Control+Shift+Up
prompt-next=Control+Shift+Down
# unicode-input=Control+Shift+u

[search-bindings]
find-prev=Up
find-next=Down
# primary-paste=Shift+Insert
# scrollback-up-page=Shift+Page_Up Shift+KP_Page_Up
# scrollback-up-half-page=
# scrollback-down-page=Shift+Page_Down Shift+KP_Page_Down.
# scrollback-down-half-page=
# scrollback-home=
# scrollback-end=

[mouse-bindings]
font-increase=none
font-decrease=none
prompt-prev=Control+Shift+BTN_WHEEL_BACK
prompt-next=Control+Shift+BTN_WHEEL_FORWARD
# primary-paste=BTN_MIDDLE
# select-begin=BTN_LEFT
# select-begin-block=Control+BTN_LEFT
# select-extend=BTN_RIGHT
# select-extend-character-wise=Control+BTN_RIGHT
# select-word=BTN_LEFT-2
# select-word-whitespace=Control+BTN_LEFT-2
# select-quote = BTN_LEFT-3
# select-row=BTN_LEFT-4
