[General]
bookmarks=/home/pavel
lastDisplay=0
maximizedWindow=true
placesPanel=true
printColor=true
printFitToPage=true
printLandscape=true
printPdfDefault=false
savedPaths=/home/pavel, /home/pavel/Desktop, /home/pavel/Documents, /home/pavel/Downloads, /home/pavel/Music, /home/pavel/Pictures, /home/pavel/Public, /home/pavel/Templates, /home/pavel/Videos
windowGeometry=@Rect(0 0 1818 1011)
