#meson setup build --prefix=/usr -Duse_system_wlroots=enabled -Duse_system_wfconfig=disabled -Dtests=disabled --buildtype=release && ninja -C build

[autostart]
autostart_wf_shell = false
notifications = mako
clipboard = zzzclip daemon
#power = sudo nvidia-smi -lgc 650,1950
sound = audio-default.sh
dbus = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE DISPLAY XDG_RUNTIME_DIR  XDG_SESSION_DESKTOP

[output:eDP-1]
mode = 1920x1080@144
position = 0,1080
mode = off

[output:DP-2]
mode = 1920x1080@144
position = 0,0
transform = normal
scale = 1.000000


[input]
3fg_drag = none
click_method = default
cursor_size = 22
cursor_theme = LiOSV
disable_touchpad_while_mouse = false
disable_touchpad_while_typing = false
drag_lock = false
gesture_sensitivity = 1.000000
kb_capslock_default_state = false
kb_numlock_default_state = false
kb_repeat_delay = 300
kb_repeat_rate = 30
left_handed_mode = false
middle_emulation = false
modifier_binding_timeout = 400
mouse_accel_profile = flat
mouse_cursor_speed = 0.000000
mouse_natural_scroll = false
mouse_scroll_speed = 1.000000
natural_scroll = true
scroll_method = default
tablet_motion_mode = default
tap_and_drag = true
tap_to_click = true
touchpad_accel_profile = default
touchpad_cursor_speed = 0.000000
touchpad_scroll_speed = 1.000000
xkb_layout = us, se, ru
xkb_model =
xkb_options = grp:win_space_toggle
xkb_rules = evdev
xkb_variant =


[core]
background_color = \#171717FF
close_top_view = <super> KEY_Q
exit = <alt> <ctrl> KEY_BACKSPACE
focus_button_with_modifiers = false
focus_buttons =
focus_buttons_passthrough = false
max_render_time = -1
plugins = autostart command simple-tile follow-focus animate foreign-toplevel session-lock preserve-output ipc ipc-rules vswitch inject-key my-activation my-rules place overview edge-hacks
preferred_decoration_mode = server
transaction_timeout = 100
vheight = 3
vwidth = 3
xwayland = false
xwayland_startup_script =


[workarounds]
all_dialogs_modal = false
app_id_mode = stock
auto_reload_config = true
config_reload_delay = 20
disable_primary_selection = true
discard_command_output = false
dynamic_repaint_delay = false
enable_input_method_v2 = false
enable_opaque_region_damage_optimizations = true
enable_so_unloading = false
focus_main_surface_instead_of_popup = false
force_frame_sync = false
force_preferred_decoration_mode = false
keep_last_toplevel_activated = false
max_buffer_size = 3840
remove_output_limits = false
use_external_output_configuration = false


[command]
binding_0 = <shift> <super> KEY_S
binding_1 = <super> KEY_V
binding_2 = <super> <ctrl>
binding_3 = <shift> <super> KEY_A
binding_4 = <super> KEY_E
binding_5 = <shift> <super> KEY_Q
binding_6 = <super> KEY_S
binding_7 = <shift> <super> KEY_D
binding_8 = <shift> <super>
binding_9 = <alt> <super> KEY_S
binding_12 = <super> KEY_SPACE
binding_13 = <super> KEY_W
binding_14 = <super> KEY_TAB
binding_16 = <super> KEY_Z
binding_17 = <shift> <super> KEY_Z
binding_18 = <shift> <super> KEY_E
binding_19 = <super> KEY_A
binding_21 = <super> KEY_GRAVE
binding_23 = <super> KEY_D
binding_24 = <super> KEY_U
binding_25 = <super> KEY_I
binding_26 = <super> KEY_K
binding_28 = <shift> <super> KEY_X
binding_29 = <super> KEY_ENTER
binding_30 = KEY_VOLUMEUP
binding_31 = KEY_VOLUMEDOWN
binding_32 = KEY_MUTE
repeatable_binding_33 = <super> KEY_PAGEUP
repeatable_binding_34 = <super> KEY_PAGEDOWN
binding_37 = <shift> <super> <alt>
binding_38 = <super> KEY_L
binding_39 = <super> KEY_M
binding_40 = <super> KEY_N
binding_41 = <super> <alt> KEY_E
binding_42 = <super> <alt> <ctrl>
binding_43 = <super> <shift> KEY_GRAVE
#binding_44 = hotspot left-bottom 10x10 0 #BTN_SIDE | BTN_EXTRA | hotspot left-top 10x10 0
binding_45 = <super> <alt> <ctrl> KEY_UP
binding_46 = <super> <alt> <ctrl> KEY_DOWN
binding_47 = <super> <alt> <ctrl> KEY_LEFT
binding_48 = <super> <alt> <ctrl> KEY_RIGHT
binding_49 = <super> <alt>
binding_51 = <ctrl>
binding_52 = KEY_ESC
binding_53 = <super> <shift> KEY_W
repeatable_binding_54 = <super> <alt> KEY_PAGEUP
repeatable_binding_55 = <super> <alt> KEY_PAGEDOWN
binding_56 = <super> <alt> KEY_M

command_37 = monstar
command_17 = open -w 13 --single-title "incognito" vivaldi --incognito
command_16 = open -w 12 --single-app-id vivaldi --exclude-title "incognito" vivaldi
command_2 = open -w 21 --single-app-id sublime_text subl --project ~/.config/sublime-text/default.sublime-project
command_42 = open -w 22 --single-app-id sublime_text_projects subl --project ~/.config/sublime-text/projects.sublime-project
command_23 = open -w 23 --single-app-id wcm wcm
command_39 = open -w 22 --single-app-id mpv mpv --player-operation-mode=pseudo-gui

command_8 =  open -w 11 --single-app-id shell kitty --single-instance --listen-on="unix:@mykitty" --class shell zsh
command_19 = open -w 31 --single-app-id yazi kitty --single-instance --listen-on="unix:@mykitty" --class yazi yazi
command_43 = open -w 33 --single-app-id btop kitty --single-instance --listen-on="unix:@mykitty" --class btop btop
command_21 = open -w 33 --single-app-id btm kitty --single-instance --listen-on=unix:@mykitty --class btm btm
command_24 = kitty-launch-or-focus.sh yzf -u
command_26 = kitty-launch-or-focus.sh nasc
command_53 = kitty-launch-or-focus.sh impala
command_25 = kitty-launch-or-focus.sh zzzclip-images.sh
command_40 = kitty-launch-or-focus.sh vpn-shell nyaazf 'naruto|-"kun.hu"|(varyg dual)'

#command_8 = open -w 11 --single-app-id shell ghostty +new-window --class shell
#command_19 = open -w 31 --single-app-id yazi ghostty +new-window --class yazi y -e yazi
#command_43 = open -w 33 --single-app-id btop ghostty +new-window --class btop b -e btop
#command_21 = open -w 33 --single-app-id btm ghostty +new-window --class btm -e btm
#command_24 = ghostty +new-window -e yzf -u
#command_26 = ghostty +new-window -e nasc
#command_53 = ghostty +new-window -e impala
#command_25 = ghostty +new-window -e zzzclip-images.sh
#command_40 = ghostty +new-window -e vpn-shell nyaazf 'naruto|-"kun.hu"|(varyg dual)'

#command_51 = dunstctl action && dunstctl close
command_51 = makoctl invoke && makoctl dismiss
#command_52 = if [ "$(dunstctl count displayed)" = "0" ]; then inject-key KEY_ESC; else dunstctl close; fi
command_52 = if [ -z "$(makoctl list)" ]; then inject-key KEY_ESC; else makoctl dismiss; fi
command_38 = hyprlock
command_12 = keyboard-layout-switcher.py
command_30 = volume.sh up
command_31 = volume.sh down
command_32 = volume.sh mute
command_54 = mic-volume.sh up
command_55 = mic-volume.sh down
command_56 = mic-volume.sh mute
command_33 = brightness.sh up
command_34 = brightness.sh down
command_46 = wlr-randr --output DP-2 --transform normal
command_45 = wlr-randr --output DP-2 --transform 180
command_48 = wlr-randr --output DP-2 --transform 90
command_47 = wlr-randr --output DP-2 --transform 270
command_29 = autostart -w
command_0 = dulcepan | wl-copy --type image/png #grim -g "$(scrop)" - | wl-copy --type image/png
command_9 = grabit -e -c
command_3 = dulcepan -f png | tesseract - stdout -l swe 2>/dev/null | wl-copy && notify-send -a osd -t 2000 "$(wl-paste)"
command_7 = hyprpicker -a
command_28 = shmooz --invert-scroll


#command_1 = cclip-menu.sh
command_1 = zzzclip-menu.sh
command_4 = emoji-picker.sh
command_41 = unicode-picker.sh
command_18 = nerdfont-picker.sh
command_5  = power-menu.sh
command_13 = iwmenu --launcher rofi
command_14 = rofi -show drun -show-icons
command_6 = alsa-switch
#command_44 = dashboard --class float --session ~/.config/kitty/session.conf
command_49 = dashboard --class float --session ~/.config/kitty/session.conf



[my-rules]
rule_10 = if app_id contains "subl" then assign-focus 21
rule_11 = if app_id contains "firefox" then assign-focus 12
rule_12 = if app_id contains "yazi" then assign-focus 31
rule_15 = if app_id contains "mpv" then assign-focus 22

[place]
mode = center

[edge-hacks]
enabled_for = app_id contains "brave" | app_id contains "vivaldi" | app_id contains "helium"
edges = bottom:1 right:1
scrollbar_fix = 80:1065
top_left_corner =
top_right_corner =
bottom_left_corner =
bottom_right_corner =

[wobbly]
friction = 3.000000
grid_resolution = 6
spring_k = 8.000000

[expo]
background = \#1A1A1AFF
duration = 200ms circle
inactive_brightness = 0.700
keyboard_interaction = true
offset = 10
toggle = <super>
transition_length = 200

[overview]
background = \#242424FF
duration = 200ms circle
active_border_color = #74AA9CFF
border_size = 3
toggle = BTN_EXTRA
toggle_all = <super>

[simple-tile]
animation_duration = 300ms circle
button_move = <super> BTN_LEFT
button_resize = <super> BTN_RIGHT
inner_gap_size = 0
keep_fullscreen_on_adjacent = false
key_focus_above = <ctrl> <super> KEY_UP
key_focus_below = <ctrl> <super> KEY_DOWN
key_focus_left = <ctrl> <super> KEY_LEFT
key_focus_right = <ctrl> <super> KEY_RIGHT
key_toggle = none
key_toggle_maximized = none
outer_horiz_gap_size = 0
outer_vert_gap_size = 0
preview_base_border = \#404080CC
preview_base_color = \#8080FF80
preview_border_width = 3
tile_by_default = !(app_id contains "float" | app_id contains "mousam")


[animate]
close_animation = zap
duration = 250ms circle
enabled_for = !(app_id is "dulcepan" | app_id is "hyprpicker" | app_id contains "mark-shot" | app_id contains "shmooz" | app_id contains "slurp" | app_id contains "scrop" | app_id contains "grabit")
fade_duration = 400ms circle
fade_enabled_for = none
fire_color = \#B22303FF
fire_duration = 300ms linear
fire_enabled_for = none
fire_particle_size = 16.000000
fire_particles = 2000
minimize_animation = zoom
open_animation = zoom
random_fire_color = false
spin_duration = 250ms linear
spin_rotations = 1
squeezimize_duration = 150ms linear
startup_duration = 0ms linear
zap_duration = 400ms linear
zoom_duration = 500ms circle
zoom_enabled_for = none


[vswitch]
binding_down = <super> KEY_DOWN
binding_last =
binding_left = <super> KEY_LEFT
binding_right = <super> KEY_RIGHT
binding_up = <super> KEY_UP
duration = 300ms circle
gap = 0
with_win_down = <shift> <super> KEY_DOWN
with_win_last =
with_win_left = <shift> <super> KEY_LEFT
with_win_right = <shift> <super> KEY_RIGHT
with_win_up = <shift> <super> KEY_UP
wraparound = false


[follow-focus]
change_output = true
change_view = true
focus_delay = 0
raise_on_top = false
threshold = 0


[preserve-output]
last_output_focus_timeout = 0
